import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForTimeout(2000);
await page.screenshot({path:'desktop-preview.png',fullPage:true});
await page.getByRole('button',{name:'Filmler',exact:true}).click();
assert(await page.locator('.library-grid .card').count()>=3);
await page.getByPlaceholder('Film, dizi veya kanal ara…').fill('Yıldızlararası');
assert.equal(await page.locator('.library-grid .card').count(),1);
await page.locator('.library-grid .card').click();
await page.locator('#favorite').click();await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Listem',exact:true}).click();
assert.equal(await page.locator('.library-grid .card').count(),1);
await page.getByRole('button',{name:'Ayarlar',exact:true}).click();
await page.locator('#playlist-file').setInputFiles({name:'test.m3u',mimeType:'text/plain',buffer:Buffer.from('#EXTM3U\n#EXTINF:-1 group-title="Ulusal",Test Kanalı\nhttps://example.com/live.m3u8\n#EXTINF:-1 group-title="Filmler",Test Film\nhttps://example.com/movie.mp4\n#EXTINF:-1 group-title="Diziler",<img src=x onerror=alert(1)>\nhttps://example.com/series.mp4')});
await page.getByRole('button',{name:'Listeyi İçe Aktar',exact:true}).click();
await page.locator('.live-grid .channel-card').first().waitFor();
assert.equal(await page.locator('.live-grid .channel-card').count(),1);
await page.getByRole('button',{name:'Diziler',exact:true}).click();
assert.equal(await page.locator('img[onerror]').count(),0);
await page.getByRole('button',{name:'Ana Sayfa',exact:true}).click();
await page.keyboard.press('ArrowRight');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');
await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('nova-playlist')).length),3);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'mobile-preview.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
assert.deepEqual(errors,[]);
await browser.close();console.log('PASS: navigation, search, favorites, M3U import, escaped content, remote focus, persistence, mobile width; no runtime errors.');
