import {portalCredentials,providerUrl,request,accountInfo,expiryLabel,saveConnection} from './provider.js';
export function openSettings({modal,overlay,connection,onSaved,escapeHtml}){
  const e=escapeHtml;
  modal(`<div class="modal-body settings"><div class="eyebrow">NOVA TV · AYARLAR</div><h2>Yayın hesabın</h2><div class="account-panel"><h3>Abonelik bilgileri</h3><p>Durum: <strong id="account-state"></strong></p><p>Bitiş tarihi: <strong id="account-expiry"></strong></p><small id="account-updated"></small><button class="secondary" id="refresh-account" type="button">Bilgileri Yenile</button></div><div class="connection-tabs" role="group" aria-label="Bağlantı yöntemi"><button type="button" class="chip selected" data-mode="url">Liste URL’si / Dosya</button><button type="button" class="chip" data-mode="portal">Portal ile Giriş</button></div><form id="playlist-form"><div id="url-fields"><label>Liste adresi<input id="playlist-url" type="password" autocomplete="off" placeholder="https://demo.example.com/playlist.m3u8" aria-label="M3U liste adresi"></label><button class="text-button" type="button" id="show-url">Adresi Göster</button><div class="or">veya dosya seç</div><label>M3U dosyası<input id="playlist-file" type="file" accept=".m3u,.m3u8,text/plain"></label></div><div id="portal-fields" hidden><label>Portal URL<input id="portal-url" type="url" placeholder="https://demo.example.com:8080" autocomplete="off"></label><label>Kullanıcı adı<input id="portal-user" placeholder="demo_kullanici" autocomplete="off" autocapitalize="none"></label><label>Şifre<input id="portal-password" type="password" placeholder="demo_sifre" autocomplete="off"></label><button type="button" class="text-button" id="show-password">Şifreyi Göster</button><p>Xtream uyumlu portal adresini kullanın.</p></div><p class="notice">Demo değerleri yalnızca alan biçimini gösterir; gerçek yayın hesabı içermez. Girdiğiniz bilgiler yalnızca bu cihazda saklanır.</p><p id="import-status" role="status"></p><button class="primary" type="submit">Listeyi İçe Aktar</button></form></div>`);
  const root=overlay.querySelector('.settings'),$=id=>root.querySelector('#'+id);
  let mode=connection?.mode||'url',activeConnection=connection,controller=null,disposed=false;
  const setMode=m=>{mode=m;root.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===m);b.setAttribute('aria-pressed',String(b.dataset.mode===m))});$('url-fields').hidden=m!=='url';$('portal-fields').hidden=m!=='portal'};
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode(mode);
  if(connection?.url)$('playlist-url').value=connection.url;
  if(connection?.credentials){$('portal-url').value=connection.credentials.base;$('portal-user').value=connection.credentials.username;$('portal-password').value=connection.credentials.password}
  const paintAccount=()=>{const a=activeConnection?.account;const statuses={Active:'Aktif',Expired:'Süresi doldu',Banned:'Engellendi',Disabled:'Devre dışı'};$('account-state').textContent=a?(typeof a.expiry==='number'&&a.expiry<Date.now()?'Süresi doldu':statuses[a.status]||a.status):'Bilgi yok';$('account-expiry').textContent=expiryLabel(a);$('account-updated').textContent=a?.checkedAt?'Son kontrol: '+new Date(a.checkedAt).toLocaleString('tr-TR'):'';$('refresh-account').disabled=!activeConnection?.credentials};
  paintAccount();$('import-status').textContent=connection?.items?.length?connection.items.length+' kayıtlı içerik':'Henüz bir yayın listesi eklenmedi.';
  [['show-url','playlist-url','Adresi'],['show-password','portal-password','Şifreyi']].forEach(([button,input,label])=>{$(button).onclick=()=>{const hidden=$(input).type==='password';$(input).type=hidden?'text':'password';$(button).textContent=label+(hidden?' Gizle':' Göster')}});
  const busy=value=>{root.querySelectorAll('button,input').forEach(b=>b.disabled=value);if(!value)paintAccount()};
  $('refresh-account').onclick=async()=>{controller=new AbortController();busy(true);$('import-status').textContent='Hesap bilgileri yenileniyor…';try{const account=await accountInfo(activeConnection.credentials,controller.signal);if(disposed)return;const updated={...activeConnection,account};try{await saveConnection(updated)}catch{}activeConnection=updated;onSaved(updated,false);paintAccount();$('import-status').textContent='Hesap bilgileri güncellendi.'}catch(error){if(!disposed)$('import-status').textContent=error.message}finally{if(!disposed)busy(false)}};
  $('playlist-form').onsubmit=async event=>{event.preventDefault();controller=new AbortController();busy(true);$('import-status').textContent='Bağlantı kuruluyor…';try{
    let url='',credentials=null,account=null,text='',warning='';
    if(mode==='portal'){credentials=portalCredentials($('portal-url').value.trim(),$('portal-user').value.trim(),$('portal-password').value);if(!credentials)throw Error('Portal adresi, kullanıcı adı ve şifreyi doldurun.');url=providerUrl(credentials,'get.php')}
    else if(!$('playlist-file').files[0]){url=$('playlist-url').value.trim();if(!url)throw Error('Bir liste adresi girin veya dosya seçin.');credentials=portalCredentials(url)}
    if(mode==='url'&&$('playlist-file').files[0])text=await $('playlist-file').files[0].text();
    else {text=await request(url,{signal:controller.signal});if(credentials&&!account){try{account=await accountInfo(credentials,controller.signal)}catch{warning=' Bitiş tarihi sağlayıcıdan alınamadı.'}}}
    if(disposed)return;
    const items=onSaved.parse(text);if(!items.length)throw Error('Listede geçerli yayın bulunamadı.');
    const next={mode,url,credentials,account,items};let storageWarning='';try{await saveConnection(next)}catch{storageWarning=' Depolama sınırlı; liste bu oturum için yüklendi.'}if(disposed)return;
    activeConnection=next;onSaved(next,true);paintAccount();$('import-status').textContent=items.length+' içerik eklendi.'+warning+storageWarning;
  }catch(error){if(!disposed)$('import-status').textContent=error.message||'Liste kaydedilemedi.'}finally{if(!disposed)busy(false)}};
  return ()=>{disposed=true;controller?.abort()};
}
